### triennale
lauree_triennali = [("Comparative, European and International Legal Studies - CEILS",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/comparative-european-and-international-legal-studies-ceils"),
("Amministrazione aziendale e diritto",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/amministrazione-aziendale-e-diritto"),
("Beni culturali",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/beni-culturali"),
("Economia e management",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/economia-e-management"),
("Filosofia",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/filosofia"),
("Fisica",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/fisica"),
("Gestione aziendale",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/gestione-aziendale"),
("Gestione aziendale (part time)",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/gestione-aziendale-part-time"),
("Informatica",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/informatica"),
("Ingegneria civile",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-civile"),
("Ingegneria dell’Informazione e delle Comunicazioni",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-dell%E2%80%99informazione-e-delle-comunicazioni"),
("Ingegneria dell'informazione e organizzazione d’impresa",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-dellinformazione-e-organizzazione-d%E2%80%99impresa"),
("Ingegneria Elettronica e delle Telecomunicazioni",
"https://infostudenti.unitn.it/it/corsi/ingegneria-elettronica-e-delle-telecomunicazioni"),
("Ingegneria per l'ambiente e il territorio",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-lambiente-e-il-territorio"),
("Ingegneria industriale",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-industriale"),
("Ingegneria Informatica, delle Comunicazioni ed Elettronica - ICE",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-informatica-delle-comunicazioni-ed-elettronica-ice"),
("Interfacce e tecnologie della comunicazione",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/interfacce-e-tecnologie-della-comunicazione"),
("Lingue moderne",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/lingue-moderne"),
("Matematica",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/matematica"),
("Scienze e tecniche di psicologia cognitiva",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/scienze-e-tecniche-di-psicologia-cognitiva"),
("Scienze e tecnologie biomolecolari",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/scienze-e-tecnologie-biomolecolari"),
("Servizio sociale",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/servizio-sociale"),
("Sociologia",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/sociologia"),
("Studi internazionali",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/studi-internazionali"),
("Studi storici e filologico-letterari",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/studi-storici-e-filologico-letterari"),
("Viticoltura ed Enologia",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/viticoltura-ed-enologia")]

### ciclo unico
lauree_ciclo_unico = [("Giurisprudenza",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali-ciclo-unico/giurisprudenza"),
("Ingegneria Edile-Architettura",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali-ciclo-unico/ingegneria-edile-architettura")]

### magistrale
lauree_magistrali = [
("Arte",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/arte"),
("Artificial Intellingence Systems - Sistemi di intelligenza artificiale - AIS",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/artificial-intellingence-systems-sistemi-di-intelligenza-artificiale-ais"),
("Biotecnologie Cellulari e Molecolari",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/biotecnologie-cellulari-e-molecolari"),
("Scienze Cognitive",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/scienze-cognitive"),
("Data Science",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/data-science"),
("Economics - MEC",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/economics-mec"),
("BEA - Behavioural and Applied Economics | Economia Comportamentale e Applicata",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/bea-behavioural-and-applied-economics-economia-comportamentale-e-applicata"),
("Economia e legislazione d'impresa",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/economia-e-legislazione-dimpresa"),
("Environmental Meteorology",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/environmental-meteorology"),
("European and International Studies | Studi Europei e Internazionali - MEIS",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/european-and-international-studies-studi-europei-e-internazionali-meis"),
("Filologia e critica letteraria",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/filologia-e-critica-letteraria"),
("Filosofia e linguaggi della modernità",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/filosofia-e-linguaggi-della-modernit%C3%A0"),
("Finanza",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/finanza"),
("Fisica",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/fisica"),
("Gestione delle organizzazioni e del territorio",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/gestione-delle-organizzazioni-e-del-territorio"),
("Global and Local Studies",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/global-and-local-studies"),
("Interazione Persona-Macchina",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/interazione-persona-macchina"),
("Informatica",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/informatica"),
("Ingegneria civile",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/ingegneria-civile"),
("Ingegneria per l'ambiente e il territorio",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/ingegneria-lambiente-e-il-territorio"),
("Ingegneria energetica",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/ingegneria-energetica"),
("Ingegneria dei materiali",
"https://infostudenti.unitn.it/it/corsi/ingegneria-dei-materiali"),
("Mechatronics engineering",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/mechatronics-engineering"),
("Ingegneria delle telecomunicazioni",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/ingegneria-delle-telecomunicazioni"),
("Ingegneria dell’Informazione e delle Comunicazioni",
"https://infostudenti.unitn.it/it/corsi/ingegneria-dell%E2%80%99informazione-e-delle-comunicazioni"),
("Letterature euroamericane, traduzione e critica letteraria",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/letterature-euroamericane-traduzione-e-critica-letteraria"),
("MAIN - Master in Innovation Management",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/main-master-innovation-management"),
("Scienze storiche",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/scienze-storiche"),
("Master in International Management - MIM",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/master-international-management-mim"),
("International Security Studies | Studi sulla Sicurezza Internazionale - MISS",
"https://infostudenti.unitn.it/it/corsi/international-security-studies"),
("Mediazione linguistica, turismo e culture",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/mediazione-linguistica-turismo-e-culture"),
("Management",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/management"),
("Management della sostenibilità e del turismo",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/management-della-sostenibilit%C3%A0-e-del-turismo"),
("Matematica",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/matematica"),
("Materials and production Engineering",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/materials-and-production-engineering"),
("Metodologia, organizzazione e valutazione dei servizi sociali",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/metodologia-organizzazione-e-valutazione-dei-servizi-sociali"),
("Psicologia",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/psicologia"),
("Quantitative and Computational Biology",
"https://infostudenti.unitn.it/it/corsi/quantitative-and-computational-biology"),
("Sociologia e ricerca sociale",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/sociologia-e-ricerca-sociale")]

course_types = ["Laurea Triennale", "Laurea a Ciclo Unico", "Laurea Magistrale"]
