### triennale
lauree_triennali = [("Comparative, European and International Legal Studies - CEILS",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/comparative-european-and-international-legal-studies-ceils"),
("Amministrazione aziendale e diritto",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/amministrazione-aziendale-e-diritto"),
("Beni culturali",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/beni-culturali"),
("Economia e management",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/economia-e-management"),
("Filosofia",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/filosofia"),
("Fisica",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/fisica"),
("Gestione aziendale",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/gestione-aziendale"),
("Gestione aziendale (part time)",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/gestione-aziendale-part-time"),
("Informatica",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/informatica"),
("Ingegneria civile",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-civile"),
("Ingegneria dell’Informazione e delle Comunicazioni",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-dell%E2%80%99informazione-e-delle-comunicazioni"),
("Ingegneria dell'informazione e organizzazione d’impresa",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-dellinformazione-e-organizzazione-d%E2%80%99impresa"),
("Ingegneria Elettronica e delle Telecomunicazioni",
"https://infostudenti.unitn.it/it/corsi/ingegneria-elettronica-e-delle-telecomunicazioni"),
("Ingegneria per l'ambiente e il territorio",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-lambiente-e-il-territorio"),
("Ingegneria industriale",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-industriale"),
("Ingegneria Informatica, delle Comunicazioni ed Elettronica - ICE",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/ingegneria-informatica-delle-comunicazioni-ed-elettronica-ice"),
("Interfacce e tecnologie della comunicazione",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/interfacce-e-tecnologie-della-comunicazione"),
("Lingue moderne",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/lingue-moderne"),
("Matematica",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/matematica"),
("Scienze e tecniche di psicologia cognitiva",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/scienze-e-tecniche-di-psicologia-cognitiva"),
("Scienze e tecnologie biomolecolari",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/scienze-e-tecnologie-biomolecolari"),
("Servizio sociale",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/servizio-sociale"),
("Sociologia",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/sociologia"),
("Studi internazionali",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/studi-internazionali"),
("Studi storici e filologico-letterari",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/studi-storici-e-filologico-letterari"),
("Viticoltura ed Enologia",
"https://infostudenti.unitn.it/it/corsi/lauree-triennali/viticoltura-ed-enologia")]

### ciclo unico
lauree_ciclo_unico = [("Giurisprudenza",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali-ciclo-unico/giurisprudenza"),
("Ingegneria Edile-Architettura",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali-ciclo-unico/ingegneria-edile-architettura")]

### magistrale
lauree_magistrali = [
("Arte",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/arte"),
("Artificial Intellingence Systems - Sistemi di intelligenza artificiale - AIS",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/artificial-intellingence-systems-sistemi-di-intelligenza-artificiale-ais"),
("Biotecnologie Cellulari e Molecolari",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/biotecnologie-cellulari-e-molecolari"),
("Scienze Cognitive",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/scienze-cognitive"),
("Data Science",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/data-science"),
("Economics - MEC",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/economics-mec"),
("BEA - Behavioural and Applied Economics | Economia Comportamentale e Applicata",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/bea-behavioural-and-applied-economics-economia-comportamentale-e-applicata"),
("Economia e legislazione d'impresa",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/economia-e-legislazione-dimpresa"),
("Environmental Meteorology",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/environmental-meteorology"),
("European and International Studies | Studi Europei e Internazionali - MEIS",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/european-and-international-studies-studi-europei-e-internazionali-meis"),
("Filologia e critica letteraria",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/filologia-e-critica-letteraria"),
("Filosofia e linguaggi della modernità",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/filosofia-e-linguaggi-della-modernit%C3%A0"),
("Finanza",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/finanza"),
("Fisica",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/fisica"),
("Gestione delle organizzazioni e del territorio",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/gestione-delle-organizzazioni-e-del-territorio"),
("Global and Local Studies",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/global-and-local-studies"),
("Interazione Persona-Macchina",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/interazione-persona-macchina"),
("Informatica",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/informatica"),
("Ingegneria civile",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/ingegneria-civile"),
("Ingegneria per l'ambiente e il territorio",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/ingegneria-lambiente-e-il-territorio"),
("Ingegneria energetica",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/ingegneria-energetica"),
("Ingegneria dei materiali",
"https://infostudenti.unitn.it/it/corsi/ingegneria-dei-materiali"),
("Mechatronics engineering",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/mechatronics-engineering"),
("Ingegneria delle telecomunicazioni",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/ingegneria-delle-telecomunicazioni"),
("Ingegneria dell’Informazione e delle Comunicazioni",
"https://infostudenti.unitn.it/it/corsi/ingegneria-dell%E2%80%99informazione-e-delle-comunicazioni"),
("Letterature euroamericane, traduzione e critica letteraria",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/letterature-euroamericane-traduzione-e-critica-letteraria"),
("MAIN - Master in Innovation Management",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/main-master-innovation-management"),
("Scienze storiche",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/scienze-storiche"),
("Master in International Management - MIM",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/master-international-management-mim"),
("International Security Studies | Studi sulla Sicurezza Internazionale - MISS",
"https://infostudenti.unitn.it/it/corsi/international-security-studies"),
("Mediazione linguistica, turismo e culture",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/mediazione-linguistica-turismo-e-culture"),
("Management",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/management"),
("Management della sostenibilità e del turismo",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/management-della-sostenibilit%C3%A0-e-del-turismo"),
("Matematica",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/matematica"),
("Materials and production Engineering",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/materials-and-production-engineering"),
("Metodologia, organizzazione e valutazione dei servizi sociali",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/metodologia-organizzazione-e-valutazione-dei-servizi-sociali"),
("Psicologia",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/psicologia"),
("Quantitative and Computational Biology",
"https://infostudenti.unitn.it/it/corsi/quantitative-and-computational-biology"),
("Sociologia e ricerca sociale",
"https://infostudenti.unitn.it/it/corsi/lauree-magistrali/sociologia-e-ricerca-sociale")]

study_plan_triennali = [
("Piano di Studio per i corsi di laurea del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-dipartimento-economia-e-management-2020-21"),
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021"),
("Piano di studio per i corsi del Dipartimento Facoltà di Giurisprudenza a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-facolta-giurisprudenza-2020-21"),
("Piano di Studio per i corsi di laurea del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-dipartimento-economia-e-management-2020-21"),
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021"),
("Piano di studio laurea in Fisica a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-laurea-fisica-2020-21"),
("Piano di Studio per i corsi di laurea del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-dipartimento-economia-e-management-2020-21"),
("Piano di Studio per i corsi di laurea del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-dipartimento-economia-e-management-2020-21"),
("Piano di studio per i corsi del Dipartimento Facoltà di Giurisprudenza a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-facolta-giurisprudenza-2020-21"),
("Piano di studio lauree Dipartimento di Ingegneria e Scienza dell'Informazione a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-disi-2020-21"),
("Piano di studio per il corso di laurea in Ingegneria Civile a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-laurea-ingegneria-civile-2020-21"),
("Piano di studio lauree Dipartimento di Ingegneria e Scienza dell'Informazione a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-disi-2020-21"),
("Piano di studio lauree Dipartimento di Ingegneria e Scienza dell'Informazione a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-disi-2020-21"),
("Piano di studio per il corso di laurea magistrale a ciclo unico in Ingegneria Edile-Architettura 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-edile-architettura-20-21"),
("Piano di studio lauree Dipartimento di Ingegneria e Scienza dell'Informazione a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-disi-2020-21"),
("Piano di studio laurea in Ingegneria Industriale"," https://infostudenti.unitn.it/it/piano-studio-ingegneria-industriale"),
("Piano di studio lauree Dipartimento di Ingegneria e Scienza dell'Informazione a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-disi-2020-21"),
("Piano di studio per il corso di laurea in Ingegneria dell'ambiente e del territorio a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-laurea-ingegneria-ambiente-territorio-2020-21"),
("Piano di studio per i corsi del Dipartimento di Psicologia e Scienze Cognitive e CIMeC a.a. 2020-21"," https://infostudenti.unitn.it/it/piano-studio-corsi-dipsco-cimec-2020-21"),
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021"),
("Piano di studio laurea in Matematica a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-laurea-matematica-2020-21"),
("Piano di studio per i corsi del Dipartimento di Psicologia e Scienze Cognitive e CIMeC a.a. 2020-21"," https://infostudenti.unitn.it/it/piano-studio-corsi-dipsco-cimec-2020-21"),
("Piano di studio laurea in Scienze e tecnologie biomolecolari a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-laurea-scienze-tecnologie-biomolecolari-2020-21"),
("Piano di studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Sociologia e Ricerca sociale a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-di-sociologia-e-ricerca-sociale"),
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021")
]

study_plan_magistrali = [
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021"),
("Piano di studio per le lauree magistrali del Dipartimento di Ingegneria e Scienza dell'Informazione 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-ingegneria-scienza-informazione-2020-21"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di studio per le lauree magistrali del Dipartimento Cibio 2020/21"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-cibio-2020-21"),
("Piano di studio per i corsi di laurea magistrale del dipartimento di Matematica 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-data-science-matematica-2020-21"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di studio per i corsi di laurea magistrale del Dipartimento di Ingegneria Civile, Ambientale e Meccanica a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-magistrali-dicam-2020-21"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021"),
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di studio per la laurea magistrale in Fisica 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-laurea-magistrale-fisica-2020-21"),
("Piano di studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Sociologia e Ricerca sociale a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-di-sociologia-e-ricerca-sociale"),
("Piano di studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Sociologia e Ricerca sociale a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-di-sociologia-e-ricerca-sociale"),
("Piano di studio per le lauree magistrali del Dipartimento di Ingegneria e Scienza dell'Informazione 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-ingegneria-scienza-informazione-2020-21"),
("Piano di studio per i corsi di laurea magistrale del Dipartimento di Ingegneria Civile, Ambientale e Meccanica a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-magistrali-dicam-2020-21"),
("Piano di studio per le lauree magistrali del Dipartimento di Ingegneria industriale 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-ingegneria-industriale-2020-21"),
("Piano di studio per le lauree magistrali del Dipartimento di Ingegneria e Scienza dell'Informazione 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-ingegneria-scienza-informazione-2020-21"),
("Piano di studio per le lauree magistrali del Dipartimento di Ingegneria e Scienza dell'Informazione 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-ingegneria-scienza-informazione-2020-21"),
("Piano di studio per i corsi di laurea magistrale del Dipartimento di Ingegneria Civile, Ambientale e Meccanica a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-magistrali-dicam-2020-21"),
("Piano di studio per i corsi di laurea magistrale del Dipartimento di Ingegneria Civile, Ambientale e Meccanica a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-studio-lauree-magistrali-dicam-2020-21"),
("Piano di studio per i corsi del Dipartimento di Psicologia e Scienze Cognitive e CIMeC a.a. 2020-21"," https://infostudenti.unitn.it/it/piano-studio-corsi-dipsco-cimec-2020-21"),
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di Studio per i corsi di laurea magistrale del Dipartimento di Economia e Management a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-dipartimento-economia-e-management-2020-21"),
("Piano di studio per i corsi di laurea magistrale del dipartimento di Matematica 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-data-science-matematica-2020-21"),
("Piano di studio per le lauree magistrali del Dipartimento di Ingegneria industriale 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-ingegneria-industriale-2020-21"),
("Piano di studio per le lauree magistrali del Dipartimento di Ingegneria industriale 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-ingegneria-industriale-2020-21"),
("Piano di Studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Lettere e Filosofia a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-lettere-e-filosofia-2020-2021"),
("Piano di studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Sociologia e Ricerca sociale a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-di-sociologia-e-ricerca-sociale"),
("Piano di studio per i corsi del Dipartimento di Psicologia e Scienze Cognitive e CIMeC a.a. 2020-21"," https://infostudenti.unitn.it/it/piano-studio-corsi-dipsco-cimec-2020-21"),
("Piano di studio per le lauree magistrali del Dipartimento Cibio 2020/21"," https://infostudenti.unitn.it/it/piano-di-studio-lauree-magistrali-cibio-2020-21"),
("Piano di studio per i corsi del Dipartimento di Psicologia e Scienze Cognitive e CIMeC a.a. 2020-21"," https://infostudenti.unitn.it/it/piano-studio-corsi-dipsco-cimec-2020-21"),
("Piano di studio per i corsi di Laurea e Laurea magistrale del Dipartimento di Sociologia e Ricerca sociale a.a. 2020/2021"," https://infostudenti.unitn.it/it/piano-di-studio-corsi-di-laurea-e-laurea-magistrale-dipartimento-di-sociologia-e-ricerca-sociale")
]

course_types = ["Laurea Triennale", "Laurea a Ciclo Unico", "Laurea Magistrale"]

departements = ["Dipartimento di Lettere e Filosofia", "Dipartimento di Ingegneria e Scienza dell'Informazione"]